[env]
TERM = "alacritty"

[font]
size = 16.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Normal"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[window]
decorations = "none"
opacity = 0.85
padding = { x = 12, y = 12 }

[colors.primary]
background = "#141814"
foreground = "#e6eedc"

[colors.cursor]
cursor = "#5cb82a"

[colors.normal]
black = "#1f241f"
red = "#e05353"
green = "#5cb82a"
yellow = "#d1cc41"
blue = "#4382ab"
magenta = "#a173bd"
cyan = "#50bfa3"
white = "#e6eedc"

[colors.bright]
black = "#2c332c"
red = "#f06c6c"
green = "#76cc43"
yellow = "#e3de59"
blue = "#5fa3cc"
magenta = "#be95db"
cyan = "#6ed9bd"
white = "#ffffff"

[terminal.shell]
program = "/usr/bin/fish"
