# alacritty-msg
# Autogenerated from man page /run/current-system/sw/share/man/man1/alacritty-msg.1.gz
complete -c alacritty-msg -s s -l socket -d 'Path for IPC socket communication.  MESSAGES'
complete -c alacritty-msg -l hold -d 'Remain open after child process exits.  OPTIONS'
complete -c alacritty-msg -l working-directory -d 'Start the shell in the specified working directory'
complete -c alacritty-msg -s T -l title -d 'Defines the window title'
complete -c alacritty-msg -l class -d 'Defines window class/app_id on X11/Wayland'
complete -c alacritty-msg -s o -l option -d 'Override configuration file options'
complete -c alacritty-msg -s e -l command -d 'Command and args to execute (must be last argument)'
complete -c alacritty-msg -s r -l reset -d 'Clear all runtime configuration changes.  OPTIONS'
complete -c alacritty-msg -s w -l window-id -d 'Window ID for the new config'

