# alacritty
# Autogenerated from man page /run/current-system/sw/share/man/man1/alacritty.1.gz
complete -c alacritty -s e -l command -d PP
complete -c alacritty -l config-file -d PP
complete -c alacritty -l embed -d PP
complete -c alacritty -s o -l option -d PP
complete -c alacritty -l socket -d PP
complete -c alacritty -s T -l title -d PP
complete -c alacritty -l working-directory -d PP

