# blkpr
# Autogenerated from man page /run/current-system/sw/share/man/man8/blkpr.8.gz
complete -c blkpr -s c -l command
complete -c blkpr -s k -l key
complete -c blkpr -s K -l oldkey
complete -c blkpr -s f -l flag
complete -c blkpr -s t -l type
complete -c blkpr -s h -l help
complete -c blkpr -s V -l version

