# chage
# Autogenerated from man page /run/current-system/sw/share/man/man1/chage.1.gz
complete -c chage -s d -l lastdayLAST_DAY -d 'Set the date when the password was last changed'
complete -c chage -s E -l expiredateEXPIRE_DATE -d 'Set the date on which the user\\*(Aqs password expires and their account will …'
complete -c chage -s h -l help -d 'Display help message and exit'
complete -c chage -s i -l iso8601 -d 'When printing dates, use YYYY-MM-DD format'
complete -c chage -s I -l inactiveINACTIVE -d 'Set the number of days of inactivity after a password has expired before the …'
complete -c chage -s l -l list -d 'Show account aging information'
complete -c chage -s m -l mindaysMIN_DAYS -d 'Set the minimum number of days between password changes to MIN_DAYS'
complete -c chage -s M -l maxdaysMAX_DAYS -d 'Set the maximum number of days during which a password is valid'
complete -c chage -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chage -s P -l prefixPREFIX_DIR -d 'Apply changes to configuration files under the root filesystem found under th…'
complete -c chage -s W -l warndaysWARN_DAYS -d 'Set the number of days of warning before a password change is required'
complete -c chage -l lastday
complete -c chage -s 1 -d 'or an empty string as the LAST_DAY clears the value and removes the password …'
complete -c chage -l expiredate
complete -c chage -l inactive
complete -c chage -l mindays
complete -c chage -l maxdays
complete -c chage -l root
complete -c chage -l prefix
complete -c chage -l warndays

