# chmem
# Autogenerated from man page /run/current-system/sw/share/man/man8/chmem.8.gz
complete -c chmem -s b -l blocks
complete -c chmem -s c -l configure
complete -c chmem -s d -l disable
complete -c chmem -s e -l enable
complete -c chmem -s g -l deconfigure
complete -c chmem -s m -l memmap-on-memory
complete -c chmem -s z -l zone
complete -c chmem -s v -l verbose
complete -c chmem -s h -l help
complete -c chmem -s V -l version

