# chvt
# Autogenerated from man page /run/current-system/sw/share/man/man1/chvt.1.gz
complete -c chvt -s C -l console -d 'the console device to be used'
complete -c chvt -s V -l version -d 'print version number'
complete -c chvt -s h -l help -d 'print this usage message.  AUTHORS Andries Brouwer <aeb@cwi'

