# clrunimap
# Autogenerated from man page /run/current-system/sw/share/man/man8/clrunimap.8.gz
complete -c clrunimap -s C -l console -d 'the console device to be used'
complete -c clrunimap -s V -l version -d 'print version number'
complete -c clrunimap -s h -l help -d 'print this usage message'

