# colcrt
# Autogenerated from man page /run/current-system/sw/share/man/man1/colcrt.1.gz
complete -c colcrt -l no-underlining
complete -c colcrt -s 2 -l half-lines
complete -c colcrt -s h -l help
complete -c colcrt -s V -l version

