# coresched
# Autogenerated from man page /run/current-system/sw/share/man/man1/coresched.1.gz
complete -c coresched -s s -l source
complete -c coresched -s d -l dest
complete -c coresched -s t -l dest-type
complete -c coresched -s v -l verbose
complete -c coresched -s h -l help
complete -c coresched -s V -l version

