# coreutils
# Autogenerated from man page /run/current-system/sw/share/man/man1/coreutils.1.gz
complete -c coreutils -l help -d 'display this help and exit'
complete -c coreutils -l version -d 'output version information and exit Built-in programs: [ b2sum base32 base64 …'

