# cpan
# Autogenerated from man page /run/current-system/sw/share/man/man1/cpan.1.gz
complete -c cpan -s a
complete -c cpan -s A
complete -c cpan -s c
complete -c cpan -s C
complete -c cpan -s D
complete -c cpan -s f
complete -c cpan -s i -d '        % cpan -f -i Module::Foo'
complete -c cpan -s F
complete -c cpan -s g
complete -c cpan -s G
complete -c cpan -s h
complete -c cpan -s I
complete -c cpan -s j
complete -c cpan -s J
complete -c cpan -s l
complete -c cpan -s L
complete -c cpan -s m
complete -c cpan -s M
complete -c cpan -s n
complete -c cpan -s O
complete -c cpan -s p
complete -c cpan -s P
complete -c cpan -s r
complete -c cpan -s s
complete -c cpan -s t
complete -c cpan -s T
complete -c cpan -s u
complete -c cpan -s v
complete -c cpan -s V
complete -c cpan -s w
complete -c cpan -s x
complete -c cpan -s X

