# dconf
# Autogenerated from man page /run/current-system/sw/share/man/man1/dconf.1.gz
complete -c dconf -s d -d 'to print the default value rather than the user-set value.  list'
complete -c dconf -s f -d 'must be specified.  compile'

