# deallocvt
# Autogenerated from man page /run/current-system/sw/share/man/man1/deallocvt.1.gz
complete -c deallocvt -s C -l console -d 'the console device to be used'
complete -c deallocvt -s V -l version -d 'print version number'
complete -c deallocvt -s h -l help -d 'print this usage message.  AUTHORS Andries Brouwer <aeb@cwi'

