# devlink-health
# Autogenerated from man page /run/current-system/sw/share/man/man8/devlink-health.8.gz
complete -c devlink-health -s V -d 'devlink health show [ {  DEV  |  DEV/PORT_INDEX  } reporter REPORTER  ]  devl…'

