# devlink-resource
# Autogenerated from man page /run/current-system/sw/share/man/man8/devlink-resource.8.gz
complete -c devlink-resource -s v -d 'devlink resource show DEV devlink resource help devlink resource set DEV path…'

