# devlink-region
# Autogenerated from man page /run/current-system/sw/share/man/man8/devlink-region.8.gz
complete -c devlink-region -s V
complete -c devlink-region -s n -d 'devlink region show [  DEV/REGION  ] devlink region new  DEV/REGION  [  snaps…'

