# devlink-port
# Autogenerated from man page /run/current-system/sw/share/man/man8/devlink-port.8.gz
complete -c devlink-port -s V
complete -c devlink-port -s n -d 'devlink port set  DEV/PORT_INDEX [  type  {  eth  |  ib  |  auto  } ] devlink…'

