# devlink-rate
# Autogenerated from man page /run/current-system/sw/share/man/man8/devlink-rate.8.gz
complete -c devlink-rate -s j -s p -s i -d 'devlink port function rate show [ {  DEV/PORT_INDEX  |  DEV/NODE_NAME  } ] de…'

