# dnssec-ksr
# Autogenerated from man page /run/current-system/sw/share/man/man1/dnssec-ksr.1.gz
complete -c dnssec-ksr -s E -d 'This option specifies the cryptographic hardware to use, when applicable'
complete -c dnssec-ksr -s e -d 'This option sets the end date for which keys or SKRs need to be generated (de…'
complete -c dnssec-ksr -s F -d 'This options turns on FIPS (US Federal Information Processing Standards) mode…'
complete -c dnssec-ksr -s f -d 'This option sets the SKR file to be signed when issuing a sign command'
complete -c dnssec-ksr -s h -d 'This option prints a short summary of the options and arguments to dnssec-ksr'
complete -c dnssec-ksr -s i -d 'This option sets the start date for which keys or SKRs need to be generated (…'
complete -c dnssec-ksr -s K -d 'This option sets the directory in which the key files are to be read or writt…'
complete -c dnssec-ksr -s k -d 'This option sets the specific dnssec-policy for which keys need to be generat…'
complete -c dnssec-ksr -s l -d 'This option provides a configuration file that contains a dnssec-policy state…'
complete -c dnssec-ksr -s o -d 'Normally when pregenerating keys, ZSKs are created'
complete -c dnssec-ksr -s V -d 'This option prints version information'
complete -c dnssec-ksr -s v -d 'This option sets the debugging level'

