# dpll
# Autogenerated from man page /run/current-system/sw/share/man/man8/dpll.8.gz
complete -c dpll -s V -o Version -d 'Print the version of the  dpll utility and exit'
complete -c dpll -s j -o json -d 'Output results in JavaScript Object Notation (JSON)'
complete -c dpll -s p
complete -c dpll -o pretty -d 'When combined with -j, generates a pretty JSON output with indentation and ne…'

