# dunstify
# Autogenerated from man page /run/current-system/sw/share/man/man1/dunstify.1.gz
complete -c dunstify -s '?' -l help -d 'X Item "-?, --help" Show help options'
complete -c dunstify -s a -l app-name -d 'X Item "-a, --app-name=NAME" Set the app name of the notification'
complete -c dunstify -s u -l urgency -d 'X Item "-u, --urgency=URG" Set the urgency level (low, normal, critical) of t…'
complete -c dunstify -s h -l hint -d 'X Item "-h, --hint=HINT" Specifies hints to pass'
complete -c dunstify -s A -l action -d 'X Item "-A, --action=ACTION" Specifies the actions to display to the user'
complete -c dunstify -s e -l transient -d 'X Item "-e, --transient" Mark the notification as transient'
complete -c dunstify -s t -l expire-time -d 'X Item "-t, --expire-time=TIMEOUT" The time in milliseconds until the notific…'
complete -c dunstify -s i -l icon -d 'X Item "-i, --icon=ICON" Specifies an icon to display with the notification'
complete -c dunstify -s I -l raw-icon -d 'X Item "-I, --raw-icon=PATH" Path to the icon to be sent as raw image data'
complete -c dunstify -s c -l category -d 'X Item "-c, --category=TYPE" The category of this notification'
complete -c dunstify -s p -l print-id -d 'X Item "-p, --print-id" Print id, which can be used to update/replace this no…'
complete -c dunstify -s r -l replace-id -d 'X Item "-r, --replace-id=ID" Set the id of this notification to The ID of the…'
complete -c dunstify -s C -l close -d 'X Item "-C, --close=ID" Close the notification with the specified ID'
complete -c dunstify -s w -l wait -d 'X Item "-w, --wait" Block until notification is closed and print close reason'
complete -c dunstify -l stack-tag -d 'X Item "--stack-tag=TAG" Set the dunst stack tag property of the notification…'
complete -c dunstify -l capabilities -d 'X Item "--capabilities" Print the server capabilities and exit'
complete -c dunstify -l serverinfo -d 'X Item "--serverinfo" Print server information and exit'
complete -c dunstify -s v -l version

