# ebtables-nft
# Autogenerated from man page /run/current-system/sw/share/man/man8/ebtables-nft.8.gz
complete -c ebtables-nft -s t -d 'CONTINUE means the next rule has to be checked.  This can be handy, f. e'
complete -c ebtables-nft -l table
complete -c ebtables-nft -s L -s Z -d 'are combined or the commands'
complete -c ebtables-nft -s N -s P -d 'are combined'
complete -c ebtables-nft -s A -l append -d 'Append a rule to the end of the selected chain'
complete -c ebtables-nft -s D -l delete -d 'Delete the specified rule or rules from the selected chain'
complete -c ebtables-nft -l Ln -d 'to list the rules with their rule number)'
complete -c ebtables-nft -s I -d command
complete -c ebtables-nft -s C -l change-counters -d 'Change the counters of the specified rule or rules from the selected chain'
complete -c ebtables-nft -l insert -d 'Insert the specified rule into the selected chain at the specified rule number'
complete -c ebtables-nft -l policy -d 'Set the policy for the chain to the given target'
complete -c ebtables-nft -s F -l flush -d 'Flush the selected chain'
complete -c ebtables-nft -l zero -d 'Set the counters of the selected chain to zero'
complete -c ebtables-nft -l list -d 'List all rules in the selected chain'
complete -c ebtables-nft -l Lx
complete -c ebtables-nft -l Lc
complete -c ebtables-nft -l Lmac2
complete -c ebtables-nft -l new-chain -d 'Create a new user-defined chain with the given name'
complete -c ebtables-nft -s X -l delete-chain -d 'Delete the specified user-defined chain'
complete -c ebtables-nft -s E -l rename-chain -d 'Rename the specified chain to a new name'
complete -c ebtables-nft -l init-table -d 'Replace the current table data by the initial table data'
complete -c ebtables-nft -s v -l verbose -d 'Verbose mode'
complete -c ebtables-nft -s V -l version -d 'Show the version of the ebtables userspace program'
complete -c ebtables-nft -s h -l help -d 'Give a brief description of the command syntax'
complete -c ebtables-nft -s j -l jump -d 'The target of the rule'
complete -c ebtables-nft -s M -l modprobe -d 'When talking to the kernel, use this program to try to automatically load mis…'
complete -c ebtables-nft -l concurrent -d 'This would use a file lock to support concurrent scripts updating the ebtable…'
complete -c ebtables-nft -l proto -d 'is an alias for this option'
complete -c ebtables-nft -l in-if -d 'is an alias for this option'
complete -c ebtables-nft -l out-if -d 'is an alias for this option'
complete -c ebtables-nft -l src -d 'is an alias for this option'
complete -c ebtables-nft -s s -d '(above) for more details on MAC addresses.  The flag'
complete -c ebtables-nft -l dst -d 'is an alias for this option'
complete -c ebtables-nft -s c -l set-counter -d 'If used with'
complete -c ebtables-nft -s m -d 'These extensions deal with functionality supported by kernel modules suppleme…'
complete -c ebtables-nft -l among-dst
complete -c ebtables-nft -l among-src -d 'arp Specify (R)ARP fields.  The protocol must be specified as ARP  or  RARP '
complete -c ebtables-nft -l ip-src -d 'is an alias for this option'
complete -c ebtables-nft -l ip-dst -d 'is an alias for this option'
complete -c ebtables-nft -l ip-proto -d 'is an alias for this option'
complete -c ebtables-nft -l ip-protocol -d 'option must be specified as TCP ,  UDP ,  DCCP  or  SCTP '
complete -c ebtables-nft -l ip-sport -d 'is an alias for this option'
complete -c ebtables-nft -l ip-dport -d 'is an alias for this option.  ip6 Specify IPv6 fields'
complete -c ebtables-nft -l ip6-src -d 'is an alias for this option'
complete -c ebtables-nft -l ip6-dst -d 'is an alias for this option'
complete -c ebtables-nft -l ip6-proto -d 'is an alias for this option'
complete -c ebtables-nft -l ip6-protocol -d 'option must be specified as TCP ,  UDP ,  DCCP  or  SCTP '
complete -c ebtables-nft -l ip6-sport -d 'is an alias for this option'
complete -c ebtables-nft -l ip6-dport -d 'is an alias for this option'
complete -c ebtables-nft -l log -d 'watcher to give limited logging, for example'
complete -c ebtables-nft -l limit -d 'Maximum average matching rate: specified as a number, with an optional /secon…'
complete -c ebtables-nft -l limit-burst -d 'Maximum initial number of packets to match: this number gets recharged by one…'
complete -c ebtables-nft -l log-level
complete -c ebtables-nft -l log-prefix
complete -c ebtables-nft -l log-ip
complete -c ebtables-nft -l log-ip6
complete -c ebtables-nft -l log-arp
complete -c ebtables-nft -l nflog
complete -c ebtables-nft -l nflog-group
complete -c ebtables-nft -l nflog-prefix
complete -c ebtables-nft -l nflog-range
complete -c ebtables-nft -l nflog-threshold
complete -c ebtables-nft -l ulog
complete -c ebtables-nft -l ulog-prefix
complete -c ebtables-nft -l ulog-nlgroup
complete -c ebtables-nft -l ulog-cprange
complete -c ebtables-nft -l ulog-qthreshold
complete -c ebtables-nft -l arpreply-mac -d 'Specifies the MAC address to reply with: the Ethernet source MAC and the ARP …'
complete -c ebtables-nft -l arpreply-target -d 'Specifies the standard target'
complete -c ebtables-nft -l to-destination
complete -c ebtables-nft -l to-dst -d 'is an alias for this option'
complete -c ebtables-nft -l dnat-target
complete -c ebtables-nft -l mark-set
complete -c ebtables-nft -l mark-or
complete -c ebtables-nft -l mark-and
complete -c ebtables-nft -l mark-xor
complete -c ebtables-nft -l mark-target
complete -c ebtables-nft -l redirect-target
complete -c ebtables-nft -l to-source
complete -c ebtables-nft -l to-src -d 'is an alias for this option'
complete -c ebtables-nft -l snat-target
complete -c ebtables-nft -l snat-arp

