# expr
# Autogenerated from man page /run/current-system/sw/share/man/man1/expr.1.gz
complete -c expr -l help -d 'display this help and exit'
complete -c expr -l version -d 'output version information and exit '

