# false
# Autogenerated from man page /run/current-system/sw/share/man/man1/false.1.gz
complete -c false -l help -d 'display this help and exit'
complete -c false -l version -d 'output version information and exit'

