# fgconsole
# Autogenerated from man page /run/current-system/sw/share/man/man1/fgconsole.1.gz
complete -c fgconsole -s n -l next-available -d 'Will show the next unallocated virtual terminal'
complete -c fgconsole -s C -l console -d 'the console device to be used'
complete -c fgconsole -s V -l version -d 'print version number'
complete -c fgconsole -s h -l help -d 'print this usage message'

