# fincore
# Autogenerated from man page /run/current-system/sw/share/man/man1/fincore.1.gz
complete -c fincore -s n -l noheadings
complete -c fincore -s b -l bytes
complete -c fincore -s c -l total
complete -c fincore -s C -l cachestat
complete -c fincore -s o -l output
complete -c fincore -l output-all
complete -c fincore -s r -l raw
complete -c fincore -s J -l json
complete -c fincore -s R -l recursive
complete -c fincore -s h -l help
complete -c fincore -s V -l version

