# fish_key_reader
# Autogenerated from man page /run/current-system/sw/share/man/man1/fish_key_reader.1.gz
complete -c fish_key_reader -s c -l continuous -d 'Begins a session where multiple key sequences can be inspected'
complete -c fish_key_reader -s h -l help -d 'Displays help about using this command'
complete -c fish_key_reader -s V -l verbose -d 'Explain what sequence was received in addition to the decoded key'
complete -c fish_key_reader -s v -l version -d 'Displays the current fish version and then exits'

