# flock
# Autogenerated from man page /run/current-system/sw/share/man/man1/flock.1.gz
complete -c flock -s c -l command
complete -c flock -s E -l conflict-exit-code
complete -c flock -s F -l no-fork
complete -c flock -s e -s x -l exclusive
complete -c flock -s n -l nb -l nonblocking
complete -c flock -s o -l close
complete -c flock -s s -l shared
complete -c flock -s u -l unlock
complete -c flock -s w -l wait -l timeout
complete -c flock -l fcntl
complete -c flock -l start
complete -c flock -l length
complete -c flock -l verbose
complete -c flock -s h -l help
complete -c flock -s V -l version

