# fold
# Autogenerated from man page /run/current-system/sw/share/man/man1/fold.1.gz
complete -c fold -s b -l bytes -d 'count bytes rather than columns'
complete -c fold -s c -l characters -d 'count characters rather than columns'
complete -c fold -s s -l spaces -d 'break after blanks, or in words greater than WIDTH'
complete -c fold -s w -l width -d 'use WIDTH columns instead of 80'
complete -c fold -l help -d 'display this help and exit'
complete -c fold -l version -d 'output version information and exit AUTHOR Written by David MacKenzie'

