# fusermount
# Autogenerated from man page /run/current-system/sw/share/man/man1/fusermount.1.gz
complete -c fusermount -s h -d 'print help'
complete -c fusermount -s V -d 'print version'
complete -c fusermount -s o -d 'mount options'
complete -c fusermount -s u -d unmount
complete -c fusermount -s q -d quiet
complete -c fusermount -s z -d 'lazy unmount'

