# genl
# Autogenerated from man page /run/current-system/sw/share/man/man8/genl.8.gz
complete -c genl -s h -o help -d 'Show summary of options'
complete -c genl -s V -o Version -d 'Show version of program'
complete -c genl -s s -o stats -o statistics -d 'Show object statistics'
complete -c genl -s d -o details -d 'Show object details'
complete -c genl -s j -o json -d 'Output results in JavaScript Object Notation (JSON)'
complete -c genl -s p -o pretty -d 'Add indentation for readability'
complete -c genl -s r -o raw -d 'Dump raw output only.  SEE ALSO ip (8)'

