# getino
# Autogenerated from man page /run/current-system/sw/share/man/man1/getino.1.gz
complete -c getino -s p -l print-pid
complete -c getino -l pidfs
complete -c getino -l cgroupns
complete -c getino -l ipcns
complete -c getino -l netns
complete -c getino -l mntns
complete -c getino -l pidns
complete -c getino -l timens
complete -c getino -l userns
complete -c getino -l utsns
complete -c getino -s h -l help
complete -c getino -s V -l version

