# getkeycodes
# Autogenerated from man page /run/current-system/sw/share/man/man8/getkeycodes.8.gz
complete -c getkeycodes -s V -l version -d 'print version number;'
complete -c getkeycodes -s h -l help -d 'print this usage message.  SEE ALSO setkeycodes (8)'

