# getunimap
# Autogenerated from man page /run/current-system/sw/share/man/man8/getunimap.8.gz
complete -c getunimap -s s -l sort -d 'sort and merge elements'
complete -c getunimap -s C -l console -d 'the console device to be used'
complete -c getunimap -s V -l version -d 'print version number'
complete -c getunimap -s h -l help -d 'print this usage message'

