# gitweb
# Autogenerated from man page /run/current-system/sw/share/man/man1/gitweb.1.gz
complete -c gitweb -l export-all -d 'option is used) allows pulling only for those repositories that have git-daem…'

