# hugetop
# Autogenerated from man page /run/current-system/sw/share/man/man1/hugetop.1.gz
complete -c hugetop -s d -l delay -d 'Refresh the display every  n in seconds'
complete -c hugetop -s n -l numa -d 'Display per NUMA node huge page information'
complete -c hugetop -s o -l once -d 'Display the output once and then exit'
complete -c hugetop -s H -l human -d 'Display human-readable output'
complete -c hugetop -s h -l help -d 'Display help text and exit'
complete -c hugetop -s V -l version -d 'Display version information and exit.  EXIT STATUS 0 Success'

