# Hyprland
# Autogenerated from man page /run/current-system/sw/share/man/man1/Hyprland.1.gz
complete -c Hyprland -s h -l help -d 'Show command usage'
complete -c Hyprland -s c -l config -d 'Specify config file to use'
complete -c Hyprland -l socket -d 'Sets the Wayland socket name (for Wayland socket handover)'
complete -c Hyprland -l wayland-fd -d 'Sets the Wayland socket file descriptor (for Wayland socket handover)'

