# ip-netns
# Autogenerated from man page /run/current-system/sw/share/man/man8/ip-netns.8.gz
complete -c ip-netns -o all -d 'option was specified then all the network namespace names will be removed'

