# ipcmk
# Autogenerated from man page /run/current-system/sw/share/man/man1/ipcmk.1.gz
complete -c ipcmk -s M -l shmem
complete -c ipcmk -s m -l posix-shmem
complete -c ipcmk -s Q -l queue
complete -c ipcmk -s q -l posix-mqueue
complete -c ipcmk -s S -l semaphore
complete -c ipcmk -s s -l posix-semaphore
complete -c ipcmk -s n -l name
complete -c ipcmk -s p -l mode
complete -c ipcmk -s h -l help
complete -c ipcmk -s V -l version

