# ipcrm
# Autogenerated from man page /run/current-system/sw/share/man/man1/ipcrm.1.gz
complete -c ipcrm -s a -l all
complete -c ipcrm -s M -l shmem-key
complete -c ipcrm -s m -l shmem-id
complete -c ipcrm -l posix-shmem
complete -c ipcrm -s Q -l queue-key
complete -c ipcrm -s q -l queue-id
complete -c ipcrm -l posix-mqueue
complete -c ipcrm -s S -l semaphore-key
complete -c ipcrm -s s -l semaphore-id
complete -c ipcrm -l posix-semaphore
complete -c ipcrm -s v -l verbose
complete -c ipcrm -s h -l help
complete -c ipcrm -s V -l version

