# irqtop
# Autogenerated from man page /run/current-system/sw/share/man/man1/irqtop.1.gz
complete -c irqtop -s o -l output
complete -c irqtop -s b -l batch
complete -c irqtop -s c -l cpu-stat
complete -c irqtop -s C -l cpu-list
complete -c irqtop -s d -l delay
complete -c irqtop -s J -l json
complete -c irqtop -s n -l iter
complete -c irqtop -s s -l sort
complete -c irqtop -s S -l softirq
complete -c irqtop -s t -l threshold
complete -c irqtop -s h -l help
complete -c irqtop -s V -l version

