# json_pp
# Autogenerated from man page /run/current-system/sw/share/man/man1/json_pp.1.gz
complete -c json_pp -s f -d '    -f from_format Reads a data in the given format from STDIN'
complete -c json_pp -s t
complete -c json_pp -o json_opt
complete -c json_pp -s v
complete -c json_pp -s V

