# kbd_mode
# Autogenerated from man page /run/current-system/sw/share/man/man1/kbd_mode.1.gz
complete -c kbd_mode -s a -l ascii -d 'set ASCII mode (XLATE)'
complete -c kbd_mode -s k -l keycode -d 'set keycode mode (MEDIUMRAW)'
complete -c kbd_mode -s s -l scancode -d 'set scancode mode (RAW)'
complete -c kbd_mode -s u -l unicode -d 'set UTF-8 mode (UNICODE)'
complete -c kbd_mode -s d -l disable -d 'set Disable mode (OFF)'
complete -c kbd_mode -s f -l force -d 'switch the mode even if it makes the keyboard unusable'
complete -c kbd_mode -s C -l console -d 'the console device to be used'

