# kill
# Autogenerated from man page /run/current-system/sw/share/man/man1/kill.1.gz
complete -c kill -s 1
complete -c kill -s n
complete -c kill -s s -l signal
complete -c kill -s l -l list
complete -c kill -s L -l table
complete -c kill -s a -l all
complete -c kill -s p -l pid
complete -c kill -s r -l require-handler
complete -c kill -l verbose
complete -c kill -s q -l queue
complete -c kill -l timeout
complete -c kill -s d -l show-process-state
complete -c kill -s h -l help
complete -c kill -s V -l version

