# kmod
# Autogenerated from man page /run/current-system/sw/share/man/man8/kmod.8.gz
complete -c kmod -s V -l version -d 'Show the program version and exit'
complete -c kmod -s h -l help -d 'Show the help message'

