# last
# Autogenerated from man page /run/current-system/sw/share/man/man1/last.1.gz
complete -c last -s a -l hostlast
complete -c last -s d -l dns
complete -c last -s f -l file
complete -c last -s F -l fulltimes
complete -c last -s i -l ip
complete -c last -s n -l limit
complete -c last -o number
complete -c last -s p -l present
complete -c last -s R -l nohostname
complete -c last -s s -l since
complete -c last -s t -l until
complete -c last -s T -l tab-separated
complete -c last -l time-format
complete -c last -s w -l fullnames
complete -c last -s x -l system
complete -c last -s h -l help
complete -c last -s V -l version

