# loadunimap
# Autogenerated from man page /run/current-system/sw/share/man/man8/loadunimap.8.gz
complete -c loadunimap -s o -l output -d 'save the old map to the FILE'
complete -c loadunimap -s C -l console -d 'the console device to be used'
complete -c loadunimap -s V -l version -d 'print version number'
complete -c loadunimap -s h -l help -d 'print this usage message.  FILES'

