# lsclocks
# Autogenerated from man page /run/current-system/sw/share/man/man1/lsclocks.1.gz
complete -c lsclocks -s J -l json
complete -c lsclocks -s n -l noheadings
complete -c lsclocks -s o -l output
complete -c lsclocks -l output-all
complete -c lsclocks -s r -l raw
complete -c lsclocks -s t -l time
complete -c lsclocks -l no-discover-dynamic
complete -c lsclocks -s d -l dynamic-clock
complete -c lsclocks -l no-discover-rtc
complete -c lsclocks -s x -l rtc
complete -c lsclocks -s c -l cpu-clock
complete -c lsclocks -s h -l help
complete -c lsclocks -s V -l version

