# lscpu
# Autogenerated from man page /run/current-system/sw/share/man/man1/lscpu.1.gz
complete -c lscpu -s a -l all
complete -c lscpu -s B -l bytes
complete -c lscpu -s b -l online
complete -c lscpu -s C -l caches
complete -c lscpu -s c -l offline
complete -c lscpu -s e -l extended
complete -c lscpu -s H -l list-columns
complete -c lscpu -l hierarchic
complete -c lscpu -s J -l json
complete -c lscpu -l output-all
complete -c lscpu -s p -l parse
complete -c lscpu -s r -l raw
complete -c lscpu -s s -l sysroot
complete -c lscpu -s x -l hex
complete -c lscpu -s y -l physical
complete -c lscpu -l arm-id
complete -c lscpu -l arm-model
complete -c lscpu -l annotate
complete -c lscpu -s h -l help
complete -c lscpu -s V -l version

