# lsirq
# Autogenerated from man page /run/current-system/sw/share/man/man1/lsirq.1.gz
complete -c lsirq -s n -l noheadings
complete -c lsirq -s i -l input
complete -c lsirq -s o -l output
complete -c lsirq -s s -l sort
complete -c lsirq -s J -l json
complete -c lsirq -s P -l pairs
complete -c lsirq -s S -l softirq
complete -c lsirq -s t -l threshold
complete -c lsirq -s C -l cpu-list
complete -c lsirq -s h -l help
complete -c lsirq -s V -l version

