# lsns
# Autogenerated from man page /run/current-system/sw/share/man/man8/lsns.8.gz
complete -c lsns -s H -l list-columns
complete -c lsns -s J -l json
complete -c lsns -s l -l list
complete -c lsns -s n -l noheadings
complete -c lsns -s o -l output
complete -c lsns -l output-all
complete -c lsns -s P -l persistent
complete -c lsns -s p -l task
complete -c lsns -s Q -l filter
complete -c lsns -s r -l raw
complete -c lsns -s t -l type
complete -c lsns -s u -l notruncate
complete -c lsns -s W -l nowrap
complete -c lsns -s T -l tree
complete -c lsns -s h -l help
complete -c lsns -s V -l version

