# lvchange
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvchange.8.gz
complete -c lvchange -l ignoreactivationskip -d 'This flag is set by default on new thin snapshot LVs'
complete -c lvchange -l poll -d 'vgchange/lvchange skip autoactivation, and defer to pvscan autoactivation'

