# lvconvert
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvconvert.8.gz
complete -c lvconvert -l type -d LV
complete -c lvconvert -s n -l name -d LV1
complete -c lvconvert -l thinpool
complete -c lvconvert -l cachepool
complete -c lvconvert -l ignoreactivationskip -d 'This flag is set by default on new thin snapshot LVs'
complete -c lvconvert -l thin -l cache -l vdo -d 'Use inferred types with care because it can lead to unexpected results'
complete -c lvconvert -l vdopool
complete -c lvconvert -l trackchanges
complete -c lvconvert -l replace

