# lvcreate
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvcreate.8.gz
complete -c lvcreate -l type
complete -c lvcreate -l thinpool
complete -c lvcreate -l cachepool
complete -c lvcreate -l ignoreactivationskip -d 'This flag is set by default on new thin snapshot LVs'
complete -c lvcreate -l thin -l cache -l vdo -d 'Use inferred types with care because it can lead to unexpected results'
complete -c lvcreate -l vdopool
complete -c lvcreate -s l -s n
complete -c lvcreate -s i -d 'but -m specifies the number of images in addition to the first image)'
complete -c lvcreate -s L -s I -s c

