# lvextend
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvextend.8.gz
complete -c lvextend -l thin -l cache -l vdo -d 'Use inferred types with care because it can lead to unexpected results'

