# lvmdevices
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvmdevices.8.gz
complete -c lvmdevices -l deviceidtype -d IDTYPE
complete -c lvmdevices -l devicesfile
complete -c lvmdevices -l devices -d device

