# lvmpersist
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvmpersist.8.gz
complete -c lvmpersist -l access -d 'br Set access to "ex" (exclusive) if the devices should be accessed by only o…'
complete -c lvmpersist -l setpersist -d 'vgchange --persist'
complete -c lvmpersist -l prtype -d 'When a PRTYPE value is specified, lvmpersist will use only that type for all …'
complete -c lvmpersist -l ourkey -d DEST
complete -c lvmpersist -l removekey -d DEST
complete -c lvmpersist -l key -d DEST
complete -c lvmpersist -l ptpl
complete -c lvmpersist -l device
complete -c lvmpersist -l vg
complete -c lvmpersist -l lockstart
complete -c lvmpersist -l persist -d 'can be included to also start PR on the new VG'

