# lvresize
# Autogenerated from man page /run/current-system/sw/share/man/man8/lvresize.8.gz
complete -c lvresize -l thin -l cache -l vdo -d 'Use inferred types with care because it can lead to unexpected results'

