# mapscrn
# Autogenerated from man page /run/current-system/sw/share/man/man8/mapscrn.8.gz
complete -c mapscrn -s o -l output -d 'save the old map to the \\,FILE\\/'
complete -c mapscrn -s C -l console -d 'the console device to be used'
complete -c mapscrn -s v -l verbose -d 'be more verbose'
complete -c mapscrn -s V -l version -d 'print version number'
complete -c mapscrn -s h -l help -d 'print this usage message.  FILES'

