# mkpasswd
# Autogenerated from man page /run/current-system/sw/share/man/man1/mkpasswd.1.gz
complete -c mkpasswd -s S -l salt -d 'Use the  STRING as salt'
complete -c mkpasswd -s R -l rounds -d 'Use  NUMBER rounds'
complete -c mkpasswd -s m -l method -d 'Compute the password using the  TYPE method'
complete -c mkpasswd -s 5 -d 'Like R --method=md5crypt '
complete -c mkpasswd -s P -l password-fd -d 'Read the password from file descriptor  NUM instead of using  getpass (3)'
complete -c mkpasswd -s s -l stdin -d Like

