# mountpoint
# Autogenerated from man page /run/current-system/sw/share/man/man1/mountpoint.1.gz
complete -c mountpoint -s d -l fs-devno
complete -c mountpoint -s q -l quiet
complete -c mountpoint -l nofollow
complete -c mountpoint -s x -l devno
complete -c mountpoint -l show
complete -c mountpoint -s h -l help
complete -c mountpoint -s V -l version

