# named-checkconf
# Autogenerated from man page /run/current-system/sw/share/man/man1/named-checkconf.1.gz
complete -c named-checkconf -s a -d 'Don\'t check the dnssec-policy\'s DNSSEC key algorithms against those supported…'
complete -c named-checkconf -s h -d 'This option prints the usage summary and exits'
complete -c named-checkconf -s j -d 'When loading a zonefile, this option instructs named \\%<#\\:std-iscman-named> …'
complete -c named-checkconf -s k -d 'Check the dnssec-policy\'s DNSSEC keys against the key files in the key-direct…'
complete -c named-checkconf -s l -d 'This option lists all the configured zones'
complete -c named-checkconf -s c -d 'This option specifies that only the "core" configuration should be checked'
complete -c named-checkconf -s i -d 'This option ignores warnings on deprecated options'
complete -c named-checkconf -s p -d 'This option prints out the named. conf \\%<#\\:std-iscman-named\\:'
complete -c named-checkconf -s t -d 'This option instructs named \\%<#\\:std-iscman-named> to chroot to directory, s…'
complete -c named-checkconf -s v -d 'This option prints the version of the named-checkconf program and exits'
complete -c named-checkconf -s x -d 'When printing the configuration files in canonical form, this option obscures…'
complete -c named-checkconf -s z -d 'This option performs a test load of all zones of type primary found in named'

