# named-rrchecker
# Autogenerated from man page /run/current-system/sw/share/man/man1/named-rrchecker.1.gz
complete -c named-rrchecker -s o -d 'This option specifies the origin to be used when interpreting names in the re…'
complete -c named-rrchecker -s p -d 'This option prints out the resulting record in canonical form'
complete -c named-rrchecker -s u -d 'This option prints out the resulting record in RFC 3597 \\%<https://\\:datatrac…'
complete -c named-rrchecker -s C -s T -s P -d 'These options do not read input'
complete -c named-rrchecker -s h -d 'This option prints out the help menu'

