# netshaper
# Autogenerated from man page /run/current-system/sw/share/man/man8/netshaper.8.gz
complete -c netshaper -s V -o Version -d 'Print the version of the  netshaper utility and exit'
complete -c netshaper -s c -d 'Configure color output'
complete -c netshaper -o help -d 'netshaper set dev DEV handle scope HANDLE_SCOPE [  id HANDLE_ID  ] bw-max BW_…'

