# nixos-generate-config
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-generate-config.8.gz
complete -c nixos-generate-config -l root -d 'If this option is given, treat the directory root as the root of the file sys…'
complete -c nixos-generate-config -l dir -d 'If this option is given, write the configuration files to the directory dir i…'
complete -c nixos-generate-config -l kernel -d 'Set the kernel in the generated configuration file'
complete -c nixos-generate-config -l force -d 'Overwrite /etc/nixos/configuration. nix (and /etc/nixos/flake'
complete -c nixos-generate-config -l flake -d 'Also generate /etc/nixos/flake. nix Ns \\&'
complete -c nixos-generate-config -l no-filesystems -d 'Omit everything concerning file systems and swap devices from the hardware co…'
complete -c nixos-generate-config -l show-hardware-config -d 'Don\'t generate configuration. nix or hardware-configuration'

