# nixos-version
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-version.8.gz
complete -c nixos-version -l hash -d 'Show the full SHA1 hash of the Git commit from which this configuration was b…'
complete -c nixos-version -l configuration-revision -d 'Show the configuration revision if available'
complete -c nixos-version -l json -d 'Print a JSON representation of the versions of NixOS and the top-level config…'

