# nixos-install
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-install.8.gz
complete -c nixos-install -l verbose -d 'Increases the level of verbosity of diagnostic messages printed on standard e…'
complete -c nixos-install -l root -d 'Defaults to /mnt Ns \\&'
complete -c nixos-install -l system -d 'If one of those options is provided, nixos-install will install the specified…'
complete -c nixos-install -l flake -d 'Build the NixOS system from the specified flake'
complete -c nixos-install -l file -d 'Build the NixOS system from the specified file'
complete -c nixos-install -l attr -d 'Build the NixOS system from nix file and use the specified attribute path fro…'
complete -c nixos-install -l channel -d 'If this option is provided, do not copy the current nixos channel to the targ…'
complete -c nixos-install -s I -d 'Add a path to the Nix expression search path'
complete -c nixos-install -l max-jobs -d 'Sets the maximum number of build jobs that Nix will perform in parallel to th…'
complete -c nixos-install -l cores -d 'Sets the value of the NIX_BUILD_CORES environment variable in the invocation …'
complete -c nixos-install -l option -d 'Set the Nix configuration option name to value Ns \\&'
complete -c nixos-install -l show-trace -d 'Causes Nix to print out a stack trace in case of Nix expression evaluation er…'
complete -c nixos-install -l keep-going -d 'Causes Nix to continue building derivations as far as possible in the face of…'
complete -c nixos-install -l log-format -d 'Set the format of log output; one of raw, internal-json, bar or bar-with-logs'
complete -c nixos-install -l help -d 'Synonym for man nixos-install Ns \\&'

