# nixos-enter
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-enter.8.gz
complete -c nixos-enter -l root -d 'The path to the NixOS system you want to enter.  It defaults to /mnt Ns \\&'
complete -c nixos-enter -l system -d 'The NixOS system configuration to use'
complete -c nixos-enter -l command -d 'The bash command to execute'
complete -c nixos-enter -l silent -d 'Suppresses all output from the activation script of the target system'

