# nixos-build-vms
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-build-vms.8.gz
complete -c nixos-build-vms -l show-trace -d 'Shows a trace of the output'
complete -c nixos-build-vms -l no-out-link -d 'Do not create a result symlink'
complete -c nixos-build-vms -s h -d 'Shows the usage of this command to the user'
complete -c nixos-build-vms -l option -d 'Set the Nix configuration option name to value Ns \\&'

