# nixos-option
# Autogenerated from man page /run/current-system/sw/share/man/man8/nixos-option.8.gz
complete -c nixos-option -s r -d 'Print all the values at or below the specified path recursively'
complete -c nixos-option -s I -d 'Add an entry to the Nix expression search path'
complete -c nixos-option -l show-trace -d 'Print eval trace'
complete -c nixos-option -s F -d 'Specify the flake containing NixOS configuration'
complete -c nixos-option -l no-flake -d 'Do not imply -flake if /etc/nixos/flake. nix exists'

