# nohup
# Autogenerated from man page /run/current-system/sw/share/man/man1/nohup.1.gz
complete -c nohup -l help -d 'display this help and exit'
complete -c nohup -l version -d 'output version information and exit '

