# ocspcheck
# Autogenerated from man page /run/current-system/sw/share/man/man8/ocspcheck.8.gz
complete -c ocspcheck -s C -d 'Specify a PEM format root certificate bundle to use for the validation of req…'
complete -c ocspcheck -s i -d 'Specify an input filename from which a DER-encoded OCSP response will be read…'
complete -c ocspcheck -s N -d 'Do not use a nonce value in the OCSP request, or validate that the nonce was …'
complete -c ocspcheck -s o -d 'Specify an output filename where the DER encoded response from the OCSP serve…'
complete -c ocspcheck -s v -d 'Increase verbosity'

