# pam_systemd
# Autogenerated from man page /run/current-system/sw/share/man/man8/pam_systemd.8.gz
complete -c pam_systemd -o auth -d 'auth      sufficient pam_unix. so auth      required   pam_deny. so'
complete -c pam_systemd -o account -d 'account   required   pam_unix. so'
complete -c pam_systemd -o password -d 'password  sufficient pam_unix'
complete -c pam_systemd -o session

