# pam_systemd_home
# Autogenerated from man page /run/current-system/sw/share/man/man8/pam_systemd_home.8.gz
complete -c pam_systemd_home -o account -d 'account   required   pam_unix. so'
complete -c pam_systemd_home -o password -d 'password  sufficient pam_unix'
complete -c pam_systemd_home -o session

