# pkexec
# Autogenerated from man page /run/current-system/sw/share/man/man1/pkexec.1.gz
complete -c pkexec -l disable-internal-agent -d 'option.  SECURITY NOTES'
complete -c pkexec -l keep-cwd -d 'is used to override this behavior'

