# pod2html
# Autogenerated from man page /run/current-system/sw/share/man/man1/pod2html.1.gz
complete -c pod2html -l nobacklink -d 'cachedir 4   --cachedir=name Specify which directory is used for storing cache'
complete -c pod2html -l noheader -d 'blocks.  help 4   --help Displays the usage message'
complete -c pod2html -l norecurse -d 'title 4   --title=title Specify the title of the resulting HTML file'

