# printf
# Autogenerated from man page /run/current-system/sw/share/man/man1/printf.1.gz
complete -c printf -l help -d 'display this help and exit'
complete -c printf -l version -d 'output version information and exit '

