# probe-bcache
# Autogenerated from man page /run/current-system/sw/share/man/man8/probe-bcache.8.gz
complete -c probe-bcache -s o -d 'return UUID in udev style for invocation by udev rule as IMPORT{program} USAG…'

