# ptargrep
# Autogenerated from man page /run/current-system/sw/share/man/man1/ptargrep.1.gz
complete -c ptargrep -l basename -s b -d 'X Item "--basename (alias -b)" When matching files are extracted, ignore the …'
complete -c ptargrep -l ignore-case -s i -d 'X Item "--ignore-case (alias -i)" Make pattern matching case-insensitive'
complete -c ptargrep -l list-only -s l -d 'X Item "--list-only (alias -l)" Print the pathname of each matching file from…'
complete -c ptargrep -l verbose -s v -d 'X Item "--verbose (alias -v)" Log debugging info to STDERR'
complete -c ptargrep -l help -s '?'

