# pvcreate
# Autogenerated from man page /run/current-system/sw/share/man/man8/pvcreate.8.gz
complete -c pvcreate -l restorefile -l norestorefile -d 'All PVs must have unique UUIDs, and LVM will prevent certain operations if mu…'
complete -c pvcreate -l uuid

