# pw-v4l2
# Autogenerated from man page /run/current-system/sw/share/man/man1/pw-v4l2.1.gz
complete -c pw-v4l2 -s h -d 'Show help'
complete -c pw-v4l2 -s r -d 'The name of the remote instance to connect to'
complete -c pw-v4l2 -s v -d 'Verbose operation'

