# rdma-resource
# Autogenerated from man page /run/current-system/sw/share/man/man8/rdma-resource.8.gz
complete -c rdma-resource -s j
complete -c rdma-resource -s d -d 'rdma resource show [  DEV/PORT_INDEX  ] rdma resource help'

