# resolvconf
# Autogenerated from man page /run/current-system/sw/share/man/man8/resolvconf.8.gz
complete -c resolvconf -s f -d 'Ignore non existent resolv. conf entries.  Only really useful for deleting'
complete -c resolvconf -s m -d 'Set the metric of the resolv. conf entry  when adding it, default of 0'
complete -c resolvconf -s p -d 'Marks the resolv. conf as private if the a command is given, otherwise resolv'
complete -c resolvconf -s x -d 'Mark the resolv'
complete -c resolvconf -s i -d 'List the keys stored, optionally matching pattern, we have resolv'
complete -c resolvconf -s L -d 'List the resolv. conf files we have, post-processed by the resolvconf'
complete -c resolvconf -s l -d 'List the resolv. conf files we have'
complete -c resolvconf -s u -d 'Force resolvconf to update all its subscribers'
complete -c resolvconf -l version -d 'Echo the resolvconf version to stdout'
complete -c resolvconf -s I -d 'Initialise the state directory /run/resolvconf'
complete -c resolvconf -s R -d 'Echo the command used to restart a service'
complete -c resolvconf -s r -d 'If the service is running then restart it'
complete -c resolvconf -s v -d 'Echo variables DOMAINS, SEARCH and NAMESERVERS so that the subscriber can con…'
complete -c resolvconf -s V -d 'Same as v except that only the information configured in resolvconf'

