# rndc
# Autogenerated from man page /run/current-system/sw/share/man/man8/rndc.8.gz
complete -c rndc -s 4 -d 'This option indicates use of IPv4 only'
complete -c rndc -s 6 -d 'This option indicates use of IPv6 only'
complete -c rndc -s b -d 'This option indicates source-address as the source address for the connection…'
complete -c rndc -s c -d 'This option indicates config-file as the configuration file instead of the de…'
complete -c rndc -s k -d 'This option indicates key-file as the key file instead of the default, /nix/s…'
complete -c rndc -s s -d 'server is the name or address of the server which matches a server statement …'
complete -c rndc -s p -d 'This option instructs BIND 9 to send commands to TCP port port instead of its…'
complete -c rndc -s q -d 'This option sets quiet mode, where message text returned by the server is not…'
complete -c rndc -s r -d 'This option instructs rndc to print the result code returned by named \\%<#\\:s…'
complete -c rndc -s t -d 'This option sets the idle timeout period for rndc to timeout seconds'
complete -c rndc -s V -d 'This option enables verbose logging'
complete -c rndc -s y -d 'This option indicates use of the key server_key from the configuration file'
complete -c rndc -o checkds -o key -o alg -o when -d 'This command informs named %<#std-iscman-named> that the DS for a specified z…'
complete -c rndc -o rollover -d 'This command allows you to schedule key rollover for a specific key (overridi…'
complete -c rndc -o status -d 'This command shows the DNSSEC signing state for the specified zone'
complete -c rndc -o step -d 'This command sends a signal to an instance of named %<#std-iscman-named> for …'
complete -c rndc -s d -s f
complete -c rndc -o redirect -d 'would specify a zone called "-redirect". ) LIMITATIONS'

