# scalar
# Autogenerated from man page /run/current-system/sw/share/man/man1/scalar.1.gz
complete -c scalar -s C
complete -c scalar -s c
complete -c scalar -l full-clone -d 'git sparse-checkout set to expand the set of directories you want to see, or …'
complete -c scalar -s b -l branch
complete -c scalar -l single-branch -l no-single-branch
complete -c scalar -l src -l no-src
complete -c scalar -l tags -l no-tags
complete -c scalar -l no-full-clone
complete -c scalar -l maintenance -l no-maintenance
complete -c scalar -l all
complete -c scalar -l path-walk -d 'option to git pack-objects by default'

