# screendump
# Autogenerated from man page /run/current-system/sw/share/man/man1/screendump.1.gz
complete -c screendump -s V -l version -d 'print version number'
complete -c screendump -s h -l help -d 'print this usage message'

