# scriptlive
# Autogenerated from man page /run/current-system/sw/share/man/man1/scriptlive.1.gz
complete -c scriptlive -l log-timing -d 'script(1) outputs to the file specified by --log-in or --log-io.  OPTIONS'
complete -c scriptlive -s c -l command
complete -c scriptlive -s I -l log-in
complete -c scriptlive -s B -l log-io
complete -c scriptlive -s E -l echo
complete -c scriptlive -s t -l timing
complete -c scriptlive -s T
complete -c scriptlive -s d -l divisor
complete -c scriptlive -s m -l maxdelay
complete -c scriptlive -s h -l help
complete -c scriptlive -s V -l version

