# setfont
# Autogenerated from man page /run/current-system/sw/share/man/man8/setfont.8.gz
complete -c setfont -s '\\' -l default8x -d 'Load default font . RI (default8x N )'
complete -c setfont -o 'h\\' -l font-height -d 'Override font height'
complete -c setfont -s d -l double -d 'Doubles the size of the font, by replicating all of its pixels vertically and…'
complete -c setfont -s o -l output-font -d 'Save previous font in R FILE '
complete -c setfont -o om -l output-consolemap -d 'Store console map in R FILE '
complete -c setfont -o ou -l output-unicodemap -d 'Save previous Unicode map in R FILE '
complete -c setfont -s O -l output-fullfont -d 'Save previous font and Unicode map in R FILE '
complete -c setfont -s m -l consolemap -d 'Load console map or Unicode console map from R FILE '
complete -c setfont -s u -l unicodemap -d 'Load Unicode table describing the font from R FILE '
complete -c setfont -s C -l console -d 'Set the font for the indicated console.  (May require root permissions. )'
complete -c setfont -s f -l force -d 'Force-load unicode map: Setfont`issues the system call to load the unicode ma…'
complete -c setfont -s R -l reset -d 'Reset the screen font, size, and Unicode mapping to the bootup defaults'
complete -c setfont -s v -l verbose -d 'Be verbose'
complete -c setfont -s V -l version -d 'Print version and exit'
complete -c setfont -s h -d option
complete -c setfont -l help -d 'Print a message describing the options and exit'

