# setkeycodes
# Autogenerated from man page /run/current-system/sw/share/man/man8/setkeycodes.8.gz
complete -c setkeycodes -s C -l console -d 'the console device to be used'
complete -c setkeycodes -s V -l version -d 'print version number'
complete -c setkeycodes -s h -l help -d 'print this usage message'

