# setleds
# Autogenerated from man page /run/current-system/sw/share/man/man1/setleds.1.gz
complete -c setleds -o num -d 'Clear or set NumLock'
complete -c setleds -o caps -d 'Clear or set CapsLock'
complete -c setleds -o scroll -d 'Clear or set ScrollLock'

