# setpgid
# Autogenerated from man page /run/current-system/sw/share/man/man1/setpgid.1.gz
complete -c setpgid -s f -l foreground
complete -c setpgid -s h -l help
complete -c setpgid -s V -l version

