# setsid
# Autogenerated from man page /run/current-system/sw/share/man/man1/setsid.1.gz
complete -c setsid -s c -l ctty
complete -c setsid -s f -l fork
complete -c setsid -s w -l wait
complete -c setsid -s h -l help
complete -c setsid -s V -l version

