# sg
# Autogenerated from man page /run/current-system/sw/share/man/man1/sg.1.gz
complete -c sg -s l -d 'Start the shell as a login shell'
complete -c sg -s c -d 'Specify a command that will be invoked by the shell using its -c'

