# showconsolefont
# Autogenerated from man page /run/current-system/sw/share/man/man8/showconsolefont.8.gz
complete -c showconsolefont -s i -l info -d 'don\'t print out the font table, just show: ROWSxCOLSxCOUNT and exit'
complete -c showconsolefont -s C -l console -d 'the console device to be used'
complete -c showconsolefont -s v -l verbose -d 'be more verbose'
complete -c showconsolefont -s V -l version -d 'print version number'
complete -c showconsolefont -s h -l help -d 'print this usage message'

