# slabtop
# Autogenerated from man page /run/current-system/sw/share/man/man1/slabtop.1.gz
complete -c slabtop -s d -l delay -d 'Refresh the display every  n in seconds'
complete -c slabtop -s s -l sort -d 'Sort by S, where S is one of the sort criteria'
complete -c slabtop -s o -l once -d 'Display the output once and then exit'
complete -c slabtop -l human -d 'Show slab sizes automatically scaled to shortest three digit unit and display…'
complete -c slabtop -s V -l version -d 'Display version information and exit'
complete -c slabtop -s h -l help -d 'Display usage information and exit'

