# spa-acp-tool
# Autogenerated from man page /run/current-system/sw/share/man/man1/spa-acp-tool.1.gz
complete -c spa-acp-tool -s h -l help -d 'Show help'
complete -c spa-acp-tool -s v -l verbose -d 'Increase verbosity by one level'
complete -c spa-acp-tool -s c -l card -d 'Select which card to probe'
complete -c spa-acp-tool -s p -l properties -d 'Additional properties to pass to ACP, e. g.  key=value '

