# ssh-copy-id
# Autogenerated from man page /run/current-system/sw/share/man/man1/ssh-copy-id.1.gz
complete -c ssh-copy-id -s i -d 'Use only the key(s) contained in identity_file (rather than looking for ident…'
complete -c ssh-copy-id -s f -d 'Forced mode: doesn\'t check if the keys are present on the remote server'
complete -c ssh-copy-id -s n -d 'do a dry-run'
complete -c ssh-copy-id -s s -d 'SFTP mode: usually the public keys are installed by executing commands on the…'
complete -c ssh-copy-id -s t -d 'the path on the target system where the keys should be added (defaults to "'
complete -c ssh-copy-id -s p -d 'Specifies the port to connect to on the remote host'
complete -c ssh-copy-id -s F -d 'These options are simply passed through untouched (with their argument) to ss…'
complete -c ssh-copy-id -s x -d 'This option is for debugging the ssh-copy-id script itself'
complete -c ssh-copy-id -s h -d 'Print Usage summary El Default behaviour without i, is to check if ssh-add -L…'

