# strace-log-merge
# Autogenerated from man page /run/current-system/sw/share/man/man1/strace-log-merge.1.gz
complete -c strace-log-merge -l help -d 'Show program usage and exit'
complete -c strace-log-merge -o tt -d 'and span across midnight.  This is because the standard'
complete -c strace-log-merge -o ttt -d 'option with strace solves this problem, as its timestamp format includes the …'

