# su
# Autogenerated from man page /run/current-system/sw/share/man/man1/su.1.gz
complete -c su -s c -l commandCOMMAND -d 'Specify a command that will be invoked by the shell using its -c'
complete -c su -s l -l login -d 'Provide an environment similar to what the user would expect had the user log…'
complete -c su -l command
complete -c su -s s -l shell
complete -c su -l preserve-environment -d 'is used, the shell specified by the $SHELL environment variable'
complete -c su -s m -s p

