# systemd-validatefs@.service
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-validatefs@.service.8.gz
complete -c 'systemd-validatefs@.service' -l root -d 'Takes an absolute path or the special string "auto"'
complete -c 'systemd-validatefs@.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-validatefs@.service' -l version -d 'Print a short version string and exit'

