# systemd-sbsign
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-sbsign.1.gz
complete -c systemd-sbsign -l output -d 'Specifies the path where to write the signed PE binary or the data to be sign…'
complete -c systemd-sbsign -l private-key -l private-key-source -l certificate -l certificate-source -d 'Set the Secure Boot private key and certificate for use with the sign verb'
complete -c systemd-sbsign -l prepare-offline-signing -d 'When this option is specified, the sign command writes the data that should b…'
complete -c systemd-sbsign -l signed-data -l signed-data-signature -d 'Configure the signed data (as written to the path specified with --output= wh…'
complete -c systemd-sbsign -s h -l help -d 'Print a short help text and exit'
complete -c systemd-sbsign -l version -d 'Print a short version string and exit'

