# systemd-mute-console
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-mute-console.1.gz
complete -c systemd-mute-console -l kernel -l pid1 -d 'Individually controls which output to mute'
complete -c systemd-mute-console -s h -l help -d 'Print a short help text and exit'
complete -c systemd-mute-console -l version -d 'Print a short version string and exit'

