# systemd-loop@.service
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-loop@.service.8.gz
complete -c 'systemd-loop@.service' -l path -d 'to properly escape a file system path'

