# systemd-pty-forward
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-pty-forward.1.gz
complete -c systemd-pty-forward -l background -d 'Change the terminal background color to the specified ANSI color as long as t…'
complete -c systemd-pty-forward -l title -d 'Change the terminal title to the specified string as long as the command runs'
complete -c systemd-pty-forward -l quiet -s q -d 'Suppresses additional informational output while running'
complete -c systemd-pty-forward -l read-only -d 'Do not accept any user input on standard input. sp Added in version 258'
complete -c systemd-pty-forward -s h -l help -d 'Print a short help text and exit'
complete -c systemd-pty-forward -l version -d 'Print a short version string and exit'

