# systemd-mstack
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-mstack.1.gz
complete -c systemd-mstack -l read-only -s r -d 'Operate in read-only mode'
complete -c systemd-mstack -l mkdir -d 'If combined with --mount the directory to mount the mount stack to is created…'
complete -c systemd-mstack -l rmdir -d 'If combined with --umount the specified directory where the mount stack is mo…'
complete -c systemd-mstack -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c systemd-mstack -l image-filter -d 'Takes an image filter string as argument, as per systemd. image-filter(7)'
complete -c systemd-mstack -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-mstack -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-mstack -l json -d 'Shows output formatted as JSON'
complete -c systemd-mstack -l mount -s m
complete -c systemd-mstack -l umount -d operation
complete -c systemd-mstack -s M
complete -c systemd-mstack -s u
complete -c systemd-mstack -s U
complete -c systemd-mstack -s h -l help
complete -c systemd-mstack -l version
complete -c systemd-mstack -l image -d '"*" policy, i. e.  all recognized file systems in the image are used'

