# systemd-keyutil
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-keyutil.1.gz
complete -c systemd-keyutil -l private-key -l private-key-source -l certificate -l certificate-source -d 'Set the private key and certificate to use'
complete -c systemd-keyutil -l signature -d 'Input PKCS#1 signature for the pkcs7 command. sp Added in version 258'
complete -c systemd-keyutil -l content -d 'Input data that corresponds to the PKCS#1 signature for the pkcs7 command, us…'
complete -c systemd-keyutil -l hash-algorithm -d 'Hash algorithm used to generate the PKCS#1 signature for the pkcs7 command'
complete -c systemd-keyutil -l output -d 'Output PKCS#7 signature for the pkcs7 command. sp Added in version 258'
complete -c systemd-keyutil -s h -l help -d 'Print a short help text and exit'
complete -c systemd-keyutil -l version -d 'Print a short version string and exit'

