# systemd-storagetm.service
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-storagetm.service.8.gz
complete -c 'systemd-storagetm.service' -l nqn -d 'Takes a string'
complete -c 'systemd-storagetm.service' -l all -s a -d 'If specified exposes all local block devices via NVMe-TCP, current and future…'
complete -c 'systemd-storagetm.service' -l list-devices -d 'Show a list of candidate block devices this command may operate on'
complete -c 'systemd-storagetm.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-storagetm.service' -l version -d 'Print a short version string and exit'

