# systemd-update-done.service
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-update-done.service.8.gz
complete -c 'systemd-update-done.service' -l root -d 'Takes a directory path as an argument'
complete -c 'systemd-update-done.service' -s h -l help -d 'Print a short help text and exit'

