# systemd-stdio-bridge
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-stdio-bridge.1.gz
complete -c systemd-stdio-bridge -l user -d 'Talk to the service manager of the calling user, rather than the service mana…'
complete -c systemd-stdio-bridge -l system -d 'Talk to the service manager of the system.  This is the implied default'
complete -c systemd-stdio-bridge -s M -l machine -d 'Execute operation on a local container'
complete -c systemd-stdio-bridge -s p -l bus-path -d 'Path to the bus address.  Default: "unix:path=/run/dbus/system_bus_socket" '
complete -c systemd-stdio-bridge -s q -l quiet -d 'Suppresses error logging on failure. sp Added in version 259'
complete -c systemd-stdio-bridge -s h -l help -d 'Print a short help text and exit'
complete -c systemd-stdio-bridge -l version -d 'Print a short version string and exit'

