# systemd-coredump
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-coredump.8.gz
complete -c systemd-coredump -l backtrace -d option
complete -c systemd-coredump -l boot -d switch

