# systemd-bsod.service
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-bsod.service.8.gz
complete -c 'systemd-bsod.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-bsod.service' -l version -d 'Print a short version string and exit'
complete -c 'systemd-bsod.service' -s c -l continuous -d 'When specified, systemd-bsod waits continuously for changes in the journal if…'
complete -c 'systemd-bsod.service' -l tty -d 'Specify the TTY to output to'

