# systemd-factory-reset
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-factory-reset.8.gz
complete -c systemd-factory-reset -l retrigger -d 'When used with the complete command retriggers all block devices, which might…'
complete -c systemd-factory-reset -l quiet -s q -d 'Suppresses the state output of status, but still sets the exit status as docu…'
complete -c systemd-factory-reset -s h -l help -d 'Print a short help text and exit'
complete -c systemd-factory-reset -l version -d 'Print a short version string and exit'

