# systemd-tpm2-clear.service
# Autogenerated from man page /run/current-system/sw/share/man/man8/systemd-tpm2-clear.service.8.gz
complete -c 'systemd-tpm2-clear.service' -l graceful -d 'Exit cleanly and execute no operation if the system does not possess a TPM ch…'
complete -c 'systemd-tpm2-clear.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-tpm2-clear.service' -l version -d 'Print a short version string and exit'

