# systemd-cryptenroll
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-cryptenroll.1.gz
complete -c systemd-cryptenroll -l tpm2-pcrs -d 'described below'
complete -c systemd-cryptenroll -l tpm2-public-key
complete -c systemd-cryptenroll -l tpm2-public-key-pcrs
complete -c systemd-cryptenroll -l tpm2-signature -d 'described below'
complete -c systemd-cryptenroll -l unlock-key-file
complete -c systemd-cryptenroll -l key-file-offset -d or
complete -c systemd-cryptenroll -l key-file-size -d 'so this file has to only contain the full key'
complete -c systemd-cryptenroll -l unlock-fido2-device
complete -c systemd-cryptenroll -l fido2-device -d 'option is also specified'
complete -c systemd-cryptenroll -l fido2-parameters-in-header
complete -c systemd-cryptenroll -l unlock-tpm2-device
complete -c systemd-cryptenroll -l password
complete -c systemd-cryptenroll -l wipe-slot -d 'in one call, see below'
complete -c systemd-cryptenroll -l recovery-key
complete -c systemd-cryptenroll -l pkcs11-token-uri
complete -c systemd-cryptenroll -l fido2-credential-algorithm
complete -c systemd-cryptenroll -l fido2-salt-file
complete -c systemd-cryptenroll -l fido2-with-client-pin
complete -c systemd-cryptenroll -l fido2-with-user-presence
complete -c systemd-cryptenroll -l fido2-with-user-verification
complete -c systemd-cryptenroll -l tpm2-device
complete -c systemd-cryptenroll -l tpm2-device-key
complete -c systemd-cryptenroll -l tpm2-seal-key-handle
complete -c systemd-cryptenroll -l tpm2-with-pin
complete -c systemd-cryptenroll -l tpm2-pcrlock
complete -c systemd-cryptenroll -l list-devices
complete -c systemd-cryptenroll -s h -l help
complete -c systemd-cryptenroll -l version
complete -c systemd-cryptenroll -l no-pager

