# systemd-inhibit
# Autogenerated from man page /run/current-system/sw/share/man/man1/systemd-inhibit.1.gz
complete -c systemd-inhibit -l what -d 'Takes a colon-separated list of one or more operations to inhibit: "shutdown"…'
complete -c systemd-inhibit -l who -d 'Takes a short, human-readable descriptive string for the program taking the l…'
complete -c systemd-inhibit -l why -d 'Takes a short, human-readable descriptive string for the reason for taking th…'
complete -c systemd-inhibit -l mode -d 'Takes "block", "delay", or "block-weak" and describes how the lock is applied'
complete -c systemd-inhibit -l list -d 'Lists all active inhibition locks instead of acquiring one'
complete -c systemd-inhibit -l no-ask-password -d 'Do not query the user for authentication for privileged operations'
complete -c systemd-inhibit -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-inhibit -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-inhibit -l json -d 'Shows output formatted as JSON'
complete -c systemd-inhibit -s h -l help -d 'Print a short help text and exit'
complete -c systemd-inhibit -l version -d 'Print a short version string and exit'

