# tipc-nametable
# Autogenerated from man page /run/current-system/sw/share/man/man8/tipc-nametable.8.gz
complete -c tipc-nametable -s h -l help -d 'Show help about last valid command'
complete -c tipc-nametable -s j -o json -d 'Output results in JavaScript Object Notation (JSON)'
complete -c tipc-nametable -s p -o pretty -d 'The default JSON format is compact and more efficient to parse but hard for m…'

