# tput
# Autogenerated from man page /run/current-system/sw/share/man/man1/tput.1.gz
complete -c tput -s T -d '-S retrieves more than one capability per invocation of  \\%tput "'
complete -c tput -s v -d 'causes  \\%tput to operate verbosely, reporting warnings'
complete -c tput -s V -d 'reports the version of  \\%ncurses associated with  \\%tput "," and exits with …'
complete -c tput -s S -d 'retrieves more than one capability per invocation of %tput '
complete -c tput -s x -d 'prevents %“tput clearc ”from attempting to clear the scrollback buffer'

