# true
# Autogenerated from man page /run/current-system/sw/share/man/man1/true.1.gz
complete -c true -l help -d 'display this help and exit'
complete -c true -l version -d 'output version information and exit'

