# ul
# Autogenerated from man page /run/current-system/sw/share/man/man1/ul.1.gz
complete -c ul -s i -l indicated
complete -c ul -s t -s T -l terminal
complete -c ul -s h -l help
complete -c ul -s V -l version

