# updatectl
# Autogenerated from man page /run/current-system/sw/share/man/man1/updatectl.1.gz
complete -c updatectl -l reboot -d 'When used with the update command, reboots the system after updates finish ap…'
complete -c updatectl -l offline -d 'When used with the list command, disables fetching metadata from the network'
complete -c updatectl -l now -d 'When used with the enable command, downloads and installs the enabled features'
complete -c updatectl -s H -l host -d 'Execute the operation remotely'
complete -c updatectl -l no-pager -d 'Do not pipe output into a pager'
complete -c updatectl -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c updatectl -s h -l help
complete -c updatectl -l version

