# uptime
# Autogenerated from man page /run/current-system/sw/share/man/man1/uptime.1.gz
complete -c uptime -l help -d 'display this help and exit'
complete -c uptime -l version -d 'output version information and exit AUTHOR Written by Joseph Arceneaux, David…'

