# uuidgen
# Autogenerated from man page /run/current-system/sw/share/man/man1/uuidgen.1.gz
complete -c uuidgen -s r -l random
complete -c uuidgen -s t -l time
complete -c uuidgen -s m -l md5
complete -c uuidgen -s s -l sha1
complete -c uuidgen -s 6 -l time-v6
complete -c uuidgen -s 7 -l time-v7
complete -c uuidgen -s n -l namespace
complete -c uuidgen -s N -l name
complete -c uuidgen -s C -l count
complete -c uuidgen -s x -l hex
complete -c uuidgen -s h -l help
complete -c uuidgen -s V -l version

