# varlinkctl
# Autogenerated from man page /run/current-system/sw/share/man/man1/varlinkctl.1.gz
complete -c varlinkctl -l more -d 'When used with call: expect multiple method replies'
complete -c varlinkctl -s E -d 'A shortcut for --more --timeout=infinity'
complete -c varlinkctl -l collect -d 'This is similar to --more, but collects all responses in a JSON array, and pr…'
complete -c varlinkctl -l oneway -d 'When used with call: do not expect a method reply'
complete -c varlinkctl -l json -d 'Selects the JSON output formatting, either "pretty" for nicely indented, colo…'
complete -c varlinkctl -s j -d 'Equivalent to --json=pretty when invoked interactively from a terminal'
complete -c varlinkctl -l quiet -s q -d 'Suppress output of method call replies. sp Added in version 257'
complete -c varlinkctl -l graceful -d 'Takes a qualified Varlink error name, i. e'
complete -c varlinkctl -l timeout -d 'Expects a timeout in seconds as parameter'
complete -c varlinkctl -l exec -d 'Once the method call issued via call completed successfully, chainload the sp…'
complete -c varlinkctl -l push-fd -d 'Takes a numeric file descriptor number as parameter'
complete -c varlinkctl -l system -l user
complete -c varlinkctl -l no-ask-password
complete -c varlinkctl -l no-pager
complete -c varlinkctl -s h -l help
complete -c varlinkctl -l version

