# vgextend
# Autogenerated from man page /run/current-system/sw/share/man/man8/vgextend.8.gz
complete -c vgextend -l labelsector -l metadatasize -l metadataignore
complete -c vgextend -l pvmetadatacopies -l dataalignment -l dataalignmentoffset
complete -c vgextend -l restorefile -l uuid

