# w
# Autogenerated from man page /run/current-system/sw/share/man/man1/w.1.gz
complete -c w -s c -l container -d 'show the container uptime instead of system uptime in the header'
complete -c w -s h -l no-header -d 'Don\'t print the header'
complete -c w -s u -l no-current -d 'Ignores the username while figuring out the current process and cpu times'
complete -c w -s s -l short -d 'Use the short format.   Don\'t print the login time, JCPU or PCPU times'
complete -c w -s t -l terminal -d 'Usually  w will use either the systemd sessions table or the utmp file to loc…'
complete -c w -s f -l from -d 'Toggle printing the  from (remote hostname) field'
complete -c w -l help -d 'Display help text and exit'
complete -c w -s i -l ip-addr -d 'Display IP address instead of hostname for from field'
complete -c w -s p -l pids -d 'Display pid of the login process/the "what" process in the "what" field'
complete -c w -s V -l version -d 'Display version information'
complete -c w -s o -l old-style -d 'Old style output.   Prints blank space for idle times less than one minute'

