# wall
# Autogenerated from man page /run/current-system/sw/share/man/man1/wall.1.gz
complete -c wall -s n -l nobanner
complete -c wall -s t -l timeout
complete -c wall -s g -l group
complete -c wall -s h -l help
complete -c wall -s V -l version

