# watch
# Autogenerated from man page /run/current-system/sw/share/man/man1/watch.1.gz
complete -c watch -s b -l beep -d 'Beep if command has a non-zero exit'
complete -c watch -s c -l color -d 'Interpret ANSI color and style sequences'
complete -c watch -s C -l no-color -d 'Do not interpret ANSI color and style sequences'
complete -c watch -s d -l differences -d 'Highlight the differences between successive updates'
complete -c watch -s e -l errexit -d 'Freeze updates on command error, and exit after a key press'
complete -c watch -s f -l follow -d 'Instead of clearing the screen at each update, watch will scroll the output s…'
complete -c watch -s g -l chgexit -d 'Exit when the visible output of command changes'
complete -c watch -s n -l interval -d 'Specify update interval.  Values smaller than 0'
complete -c watch -s p -l precise -d 'Execute command --interval seconds after its previous run started, instead of…'
complete -c watch -s q -l equexit -d 'Exit when output of command does not change for the given number of cycles'
complete -c watch -s r -l no-rerun -d 'Do not run the program on terminal resize, the output of the program will re-…'
complete -c watch -s s -l shotsdir -d 'Directory to save screenshots into'
complete -c watch -s t -l no-title -d 'Turn off the header normally shown at the top of the screen'
complete -c watch -s w -l no-wrap -d 'Turn off line wrapping'
complete -c watch -s x -l exec -d 'Pass command to an  exec (3) call instead of sh -c'
complete -c watch -s h -l help -d 'Display help text and exit'
complete -c watch -l eqexit
complete -c watch -s v -l version -d 'Display version information and exit.  KEY CONTROL'

