# wcurl
# Autogenerated from man page /run/current-system/sw/share/man/man1/wcurl.1.gz
complete -c wcurl -l curl-options -l curl-options -d 'Specify extra options to be passed when invoking curl'
complete -c wcurl -s o -s O -l output -l output -d 'Use the provided output path instead of getting it from the URL'
complete -c wcurl -l no-decode-filename -d 'Do not percent-decode the output filename, even if the percent-encoding in th…'
complete -c wcurl -l dry-run -d 'Do not actually execute curl, print what would be invoked'
complete -c wcurl -s V -l version -d 'Print version information'
complete -c wcurl -s h -l help -d 'Print help message'

