# wpctl
# Autogenerated from man page /run/current-system/sw/share/man/man1/wpctl.1.gz
complete -c wpctl -s k -l nick -d 'Display device and node nicknames instead of descriptions'
complete -c wpctl -s n -l name -d 'Display device and node names instead of descriptions get-volume'
complete -c wpctl -s r -l referenced -d 'Show objects that are referenced in properties'
complete -c wpctl -s a -l associated -d 'Show associated objects set-default'
complete -c wpctl -s p -l pid -d 'Treat ID as a process ID and affect all nodes associated with it'
complete -c wpctl -s l -l limit -d 'Limit final volume to below this value (floating point, 1'
complete -c wpctl -s d -l delete -d 'Delete the saved setting value (no KEY means delete all)'
complete -c wpctl -s s -l save -d 'Save the setting value (no KEY means save all, no VAL means current value)'
complete -c wpctl -l reset -d 'Reset the setting to its default value Behavior:'

