# xdg-terminal
# Autogenerated from man page /run/current-system/sw/share/man/man1/xdg-terminal.1.gz
complete -c xdg-terminal -l help -d 'Show command synopsis'
complete -c xdg-terminal -l manual -d 'Show this manual page'
complete -c xdg-terminal -l version -d 'Show the xdg-utils version information'

