# xsubpp
# Autogenerated from man page /run/current-system/sw/share/man/man1/xsubpp.1.gz
complete -c xsubpp -o hiertype -d 'X Item "-hiertype" Retains \\*(Aq::\\*(Aq in type names so that C++ hierarchica…'
complete -c xsubpp -o except -d 'X Item "-except" Adds exception handling stubs to the C code'
complete -c xsubpp -o typemap -d 'X Item "-typemap typemap" Indicates that a user-supplied typemap should take …'
complete -c xsubpp -o output -d 'X Item "-output filename" Specifies the name of the output file to generate'
complete -c xsubpp -s v -d 'X Item "-v" Prints the xsubpp version number to standard output, then exits'
complete -c xsubpp -o prototypes -d 'X Item "-prototypes" By default xsubpp will not automatically generate protot…'
complete -c xsubpp -o noversioncheck -d 'X Item "-noversioncheck" Disables the run time test that determines if the ob…'
complete -c xsubpp -o nolinenumbers -d 'X Item "-nolinenumbers" Prevents the inclusion of \\*(Aq#line\\*(Aq directives …'
complete -c xsubpp -o nooptimize -d 'X Item "-nooptimize" Disables certain optimizations'
complete -c xsubpp -o noinout -d 'X Item "-noinout" Disable recognition of \\f(CW\\*(C`IN\\*(C\', \\f(CW\\*(C`OUT_LIS…'
complete -c xsubpp -o noargtypes -d 'X Item "-noargtypes" Disable recognition of ANSI-like descriptions of functio…'
complete -c xsubpp -o C++ -d 'X Item "-C++" Currently doesn\\*(Aqt do anything at all'
complete -c xsubpp -s s -o strip

